# Generated by Django 2.0.7 on 2018-10-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180922_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(default=None, max_length=10, verbose_name='真名'),
            preserve_default=False,
        ),
    ]
