# Generated by Django 2.0.7 on 2018-10-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181017_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(default='abc', max_length=10, verbose_name='真名'),
            preserve_default=False,
        ),
    ]
