# Generated by Django 2.0.7 on 2018-10-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181017_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='realname',
            field=models.CharField(help_text='长度不大于10', max_length=10, verbose_name='真名'),
        ),
    ]
