# Generated by Django 2.0.6 on 2018-07-23 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tft.models.order


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_time', models.DateTimeField(blank=True, null=True, verbose_name='生产签核时间')),
                ('c_time', models.DateTimeField(blank=True, null=True, verbose_name='责任工程签核时间')),
                ('recipe_close', models.CharField(max_length=10, verbose_name='Recipe关闭人员')),
                ('recipe_confirm', models.CharField(max_length=10, verbose_name='Recipe确认人员')),
                ('rejected', models.BooleanField(default=False, verbose_name='是否拒签')),
                ('reason', models.TextField(blank=True, max_length=100, null=True, verbose_name='拒签理由')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('c_signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='c_startaudits', to=settings.AUTH_USER_MODEL, verbose_name='责任工程签核')),
            ],
            options={
                'verbose_name': '停机签核',
                'verbose_name_plural': '停机签核',
            },
        ),
        migrations.CreateModel(
            name='Eq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='装置名')),
            ],
            options={
                'verbose_name': '装置',
                'verbose_name_plural': '装置',
            },
        ),
        migrations.CreateModel(
            name='EqKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='装置类别')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eqkinds', to='auth.Group', verbose_name='科室')),
            ],
            options={
                'verbose_name': '装置类别',
                'verbose_name_plural': '装置类别',
            },
        ),
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '流水号',
                'verbose_name_plural': '流水号',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=14, null=True, verbose_name='批次')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '批次',
                'verbose_name_plural': '批次',
            },
        ),
        migrations.CreateModel(
            name='LotInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=4, verbose_name='机种')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='大小')),
                ('height', models.CharField(blank=True, max_length=10, null=True, verbose_name='高度')),
            ],
            options={
                'verbose_name': '机种信息',
                'verbose_name_plural': '机种信息',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=tft.models.order.default_order_sn, max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('status', models.CharField(choices=[('0', '未知'), ('1', '待审核'), ('2', '审核中'), ('3', '停机拒签'), ('4', '停机完成'), ('5', '待 QC 签核复机'), ('6', '驳回复机申请'), ('7', '待生产签核'), ('8', '完成部分复机'), ('9', '完成复机')], default='0', max_length=2, verbose_name='状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='开单时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('found_step', models.CharField(max_length=30, verbose_name='发现站点')),
                ('found_time', models.DateTimeField(verbose_name='发现时间')),
                ('eq', models.CharField(max_length=50, verbose_name='停机设备')),
                ('kind', models.CharField(max_length=30, verbose_name='停机机种')),
                ('step', models.CharField(max_length=50, verbose_name='停机站点')),
                ('reason', models.TextField(max_length=100, verbose_name='停机原因')),
                ('users', models.CharField(max_length=10, verbose_name='通知生产人员')),
                ('charge_users', models.CharField(max_length=10, verbose_name='通知制程人员')),
                ('desc', models.TextField(max_length=300, verbose_name='异常描述')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='受害开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='受害结束时间')),
                ('lot_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='受害批次数')),
                ('lots', models.TextField(blank=True, max_length=100, null=True, verbose_name='异常批次/基板')),
                ('condition', models.TextField(max_length=200, verbose_name='复机条件')),
                ('defect_type', models.NullBooleanField(default=None, verbose_name='绝对不良')),
                ('charge_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargeorders', to='auth.Group', verbose_name='责任工程')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='startorders', to='auth.Group', verbose_name='开单工程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startorders', to=settings.AUTH_USER_MODEL, verbose_name='开单人员')),
            ],
            options={
                'verbose_name': '停机单',
                'verbose_name_plural': '停机单',
            },
        ),
        migrations.CreateModel(
            name='RecoverAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_time', models.DateTimeField(blank=True, null=True, verbose_name='品质签核时间')),
                ('p_time', models.DateTimeField(blank=True, null=True, verbose_name='生产签核时间')),
                ('rejected', models.BooleanField(default=False, verbose_name='拒签')),
                ('reason', models.TextField(blank=True, max_length=100, null=True, verbose_name='拒签理由')),
                ('p_signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p_recoveraudit', to=settings.AUTH_USER_MODEL, verbose_name='生产领班签核')),
                ('qc_signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_recoveraudits', to=settings.AUTH_USER_MODEL, verbose_name='工程品质签核')),
            ],
            options={
                'verbose_name': '复机签核',
                'verbose_name_plural': '复机签核',
            },
        ),
        migrations.CreateModel(
            name='RecoverOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('solution', models.TextField(max_length=200, verbose_name='责任单位对策说明')),
                ('explain', models.TextField(max_length=200, verbose_name='先行lot结果说明')),
                ('partial', models.BooleanField(default=False, verbose_name='部分复机')),
                ('eq', models.CharField(max_length=50, verbose_name='停机设备')),
                ('kind', models.CharField(blank=True, max_length=30, null=True, verbose_name='部分复机机种')),
                ('step', models.CharField(blank=True, max_length=50, null=True, verbose_name='部分复机站点')),
                ('appl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoverorders', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoverorders', to='tft.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '复机单',
                'verbose_name_plural': '复机单',
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='tft.Order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remarks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '生产批注',
                'verbose_name_plural': '生产批注',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=tft.models.order.report_handler, verbose_name='调查报告')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tft.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '调查报告',
                'verbose_name_plural': '调查报告',
            },
        ),
        migrations.AddField(
            model_name='recoveraudit',
            name='recover_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='tft.RecoverOrder', verbose_name='复机单'),
        ),
        migrations.AddField(
            model_name='eq',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eqs', to='tft.EqKind', verbose_name='装置类别'),
        ),
        migrations.AddField(
            model_name='audit',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startaudit', to='tft.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='audit',
            name='p_signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p_startaudit', to=settings.AUTH_USER_MODEL, verbose_name='生产领班签核'),
        ),
    ]
