# Generated by Django 2.0.7 on 2018-10-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kind',
            field=models.CharField(max_length=70, verbose_name='停机机种'),
        ),
        migrations.AlterField(
            model_name='recoverorder',
            name='kind',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='部分复机机种'),
        ),
    ]
