# Generated by Django 2.0.6 on 2018-07-23 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mod_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modstartorders', to=settings.AUTH_USER_MODEL, verbose_name='修改人员'),
        ),
    ]
