# Generated by Django 2.0.6 on 2018-07-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0004_auto_20180725_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': '工作流', 'verbose_name_plural': '工作流'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': '订单节点', 'verbose_name_plural': '订单节点'},
        ),
        migrations.AlterField(
            model_name='flow',
            name='next_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tft.Node', verbose_name='下一节点'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='pre_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tft.Node', verbose_name='上一节点'),
        ),
    ]
