# Generated by Django 2.0.6 on 2018-07-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0005_auto_20180725_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='next_node',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='order',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='pre_node',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '未知'), ('1', '（停机）待生产签核'), ('2', '（停机）待责任工程签核'), ('3', '（停机）拒签'), ('4', '（停机）完成'), ('5', '（复机）待QC签核'), ('6', '（复机）待生产签核'), ('7', '（复机）拒签'), ('8', '（部分复机）完成'), ('9', '（复机）完成')], default='0', max_length=2, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='Flow',
        ),
    ]
