# Generated by Django 2.0.6 on 2018-07-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0006_auto_20180726_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='next',
            field=models.CharField(blank=True, choices=[('0', '未知'), ('1', '（停机）待生产签核'), ('2', '（停机）待责任工程签核'), ('3', '（停机）拒签'), ('4', '（停机）完成'), ('5', '（复机）待QC签核'), ('6', '（复机）待生产签核'), ('7', '（复机）拒签'), ('8', '（部分复机）完成'), ('9', '（复机）完成')], default='0', max_length=2, null=True, verbose_name='下一步'),
        ),
    ]
