# Generated by Django 2.0.6 on 2018-07-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0007_order_next'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': '停机单', 'verbose_name_plural': '停机单'},
        ),
    ]
