# Generated by Django 2.0.6 on 2018-08-03 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tft', '0011_auto_20180801_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverorder',
            name='mod_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modrecoverorders', to=settings.AUTH_USER_MODEL, verbose_name='修改人员'),
        ),
        migrations.AddField(
            model_name='recoverorder',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
