# Generated by Django 2.0.7 on 2018-08-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0012_auto_20180803_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='ShortcutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100, verbose_name='内容')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tft.Shortcut', verbose_name='标题')),
            ],
        ),
        migrations.RemoveField(
            model_name='eq',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='eqkind',
            name='group',
        ),
        migrations.DeleteModel(
            name='Eq',
        ),
        migrations.DeleteModel(
            name='EqKind',
        ),
    ]
