# Generated by Django 2.0.7 on 2018-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0013_auto_20180806_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcut',
            options={'verbose_name': '快捷标题', 'verbose_name_plural': '快捷标题'},
        ),
        migrations.AlterModelOptions(
            name='shortcutcontent',
            options={'verbose_name': '快捷内容', 'verbose_name_plural': '快捷内容'},
        ),
        migrations.AlterField(
            model_name='shortcutcontent',
            name='content',
            field=models.CharField(max_length=30, verbose_name='内容'),
        ),
    ]
