# Generated by Django 2.0.7 on 2018-09-04 01:51

from django.db import migrations, models
import tft.models.order


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0016_auto_20180830_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to=tft.models.order.report_handler, verbose_name='调查报告'),
        ),
    ]
