# Generated by Django 2.0.7 on 2018-09-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0018_auto_20180911_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoverorder',
            options={'verbose_name': '复机单', 'verbose_name_plural': '复机单'},
        ),
    ]
