# Generated by Django 2.0.7 on 2018-09-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0019_auto_20180911_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recoverorder',
            options={'ordering': ('-created',), 'verbose_name': '复机单', 'verbose_name_plural': '复机单'},
        ),
    ]
