# Generated by Django 2.0.7 on 2018-10-17 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0020_auto_20180913_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.IntegerField(verbose_name='状态代码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='tft.Order', verbose_name='订单')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
