# Generated by Django 2.0.7 on 2018-10-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_remove_group_department'),
        ('tft', '0021_orderflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(verbose_name='标记值')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='auth.Group', verbose_name='科室')),
            ],
        ),
        migrations.AlterModelOptions(
            name='orderflow',
            options={'ordering': ('created',), 'verbose_name': '状态日志', 'verbose_name_plural': '状态日志'},
        ),
    ]
