# Generated by Django 2.0.7 on 2018-10-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tft', '0022_auto_20181022_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': '标记值', 'verbose_name_plural': '标记值'},
        ),
        migrations.AlterField(
            model_name='mark',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='auth.Group', verbose_name='科室'),
        ),
    ]
